config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do 
      get :feeds
    end

    member do
      get :dashboard
    end
  end
  
  resources :users, only: [:show, :edit, :update]

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants 
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
<<<<<<< HEAD
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
=======
  has_many :favorited_restaurants, thourgh: :favorites, source: :restaurant
>>>>>>> a50d84c42992659eda0c1e93f51e26e328690f76

  def admin?
    self.role == "admin"
  end


end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
 before_action :authenticate_admin

  private
  
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]
  before_action :set_category, only: [:update, :destroy]


  def index
    @categories = Category.all
      if params[:id]
        set_category
      else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end 


  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "Category was successfully updated"
    else
      @category = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "Category was successfully deleted"
    redirect_to admin_categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurants_path
      flash[:notice] = "restaurant was successfully created"
    else
      render :new
      flash[:alert] = "restaurant was failed to create"
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
      flash[:notice] = "Restaurant was successfully updated!!"
    else
      render :edit
      flash[:notice] = "Restaurant was failed to update"
    end
  end 

private
  


  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show 
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  

  def show
    @commented_restaurants = @user.restaurants.uniq
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end


private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>

  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>

  <% if @category.errors.any? %>
    <%= @category.errors.full_messages.to_sentence %>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', admin_categories_path(id: category.id) %>
              <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %></td>
          </tr>
          

          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="form-inline" >
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<div class = "form container">
  <%= form_for  [:admin, @restaurant] do |f| %>

    <div class="form-group">
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt:true}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :tel, "Tel" %>
      <%= f.text_field :tel, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :opening_hours, "Opening Hours" %>
      <%= f.text_field :opening_hours, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description %>
    </div>
    
    <div class="form-group">
      <%= f.label :image, "Photo" %>
      <%= image_tag @restaurant.image, width: '600px' if @restaurant.image? %>
      <%= f.file_field :image %>
    </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container"> 
      <a class="navbar-brand" href="#">餐廳評論網後台</a>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"><%= link_to 'New Restaurant', new_admin_restaurant_path %>
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


 <!-- Page Content -->
  <div class="container">

    <!-- Page Heading -->
      <h1 class="my-4">Page Heading
        <small>Secondary Text</small>
      </h1>

        <div>
          <%= link_to 'Restaurant', admin_restaurants_path %> |
          <%= link_to 'Categories', admin_categories_path %>
        </div>
        


    <div class="row">
      <% @restaurants.each do |restaurant| %>
        <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><%= image_tag restaurant.image, size:"700x400", class: "img-thumbnail" %></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#"><%= restaurant.name %></a>
              </h4>
              <h4 class="card-title">
                <a href="#"><%= restaurant.category.name %></a>
              </h4>
              <p class="card-text"><%= simple_format(restaurant.description) %></p>
              <h4 class="card-title">
                <a href="#"><%= link_to 'Show', admin_restaurant_path(restaurant) %></a>
              </h4>
              <h4 class="card-title">
                <a href="#"><%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %></a>
              </h4>
              <h4 class="card-title">
                <a href="#"><%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm:"Are you sure?"} %></a>
              </h4>
            </div>
          </div>
        </div>
        <% end %>
        </div>
    </div>

    <ul class="pagination justify-content-center">
     <%= paginate @restaurants %>
    </ul>

  </div>

  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
    </div>
  </footer>

</body>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  
  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>
  
  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= @restaurant.category.name %><br>
Opning Hours: <%= @restaurant.opening_hours %><br>
Tel: <%= @restaurant.tel %><br>
Address: <%= @restaurant.address %><br>
Description:<%= @restaurant.description %><br>

<br>

<%= link_to 'Back to Index', admin_restaurants_path %>

app/views/categories/show.html.erb
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container"> 
      <a class="navbar-brand" href="#">餐廳評論網</a>
    </div>
  </nav>


 <!-- Page Content -->
  <div class="container">

    <div class="row">
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to "全部餐廳", root_path %></li>
        <% @categories.each do |category| %>
        <li role="presentation" class="<%= "active" if category == @category %>"><%= link_to category.name, category_path(category) %></li>
        <% end %>
      </ul>

    </div>

    <%= render partial: "shared/restaurant_list" %>

</body>

app/views/restaurants/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %>'s Dashboard</h1>
      <hr>
      <ul>
        <li>有 <%= @restaurant.comments.count %> 筆評論</li>
        <li>這家餐廳的平均價位為 $XXX</li>
        <li>有 XX 人收藏這家餐廳</li>
      </ul>

    </div>
  </div>
</div>

app/views/restaurants/feeds.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presnetation" class="active">
        <%= link_to '最新動態', feeds_restaurants_path %>        
      </li>
    </ul>
  </div>
</div>

<br>

<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳最新動態</h1>
      <hr>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新餐廳</div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
              <div>
                <h4><%= link_to restaurant.name, restaurant_path(restaurant) %> 
                  <small><%= restaurant.category.name %></small>
                </h4>
                <p><%= truncate(restaurant.description, length: 80) %></p>
                <hr>
              </div>          
            <% end %>
          </div>  
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新評論</div>
          <div class="panel-body">
              <% @recent_comments.each do |comment| %>
              <div>
                <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
                <p><%= truncate(comment.content, length: 80) %><small> - by <%= link_to comment.user.name, user_path(comment.user) %></small></p>
                <hr>
              </div>          
            <% end %>
          </div>  
        </div>
      </div>
    </div>

  </div>
</div>

app/views/restaurants/index.html.erb
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container"> 
      <a class="navbar-brand" href="#">餐廳評論網</a>
    </div>
  </nav>


  <div class= "container">
    <div class="row">

      <ul class="nav nav-tabs">
        <li role="presentation" class="active">
          <%= link_to '首頁', root_path %>
        </li>
      
        <li role="presentation">
          <%= link_to '最新動態', feeds_restaurants_path %>          
        </li>
      </ul>

    </div>
  </div>

<br>

 <!-- Page Content -->
  <div class="container">

    <div class="row">
      <ul class="nav nav-pills">
        <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
        <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
        <% end %>
      </ul>

    </div>

        <%= render partial: "shared/restaurant_list" %>

</body>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
<!--       <%= image_tag @restaurant.image, class: "img-responsive center-block" %> -->
      <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded">
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
    </div>

    <div class="clearfix"></div>
    <hr>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @restaurant.comments.each do |comment| %>
      <div>
        <h4><%= comment.user.name %></h4>
        <p><%= simple_format comment.content %></p>
        <p class="text-muted">
          <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
          <% if current_user.admin?  %>
             <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
          <% end %>
        </p>
      </div>
     <hr>
    <% end %>

  

   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>

  

  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :avatar, "頭像上傳" %>
          <%= image_tag @user.avatar if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>

        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <div class="page-header">
        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded">
           <!-- <%= image_tag @user.avatar, class: "img-responsive img-rounded" %> -->
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>
      <br>

      <div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @commented_restaurants.count%></strong></strong> 評論過餐廳 </h3>
          </div>

          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
             <div class= "my-restaurant">
                <div>
                  <!-- <%= image_tag restaurant.image, size:"350x350", class: "img-thumbnail" %> -->
                  <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded">
                </div>    
              <h5><%= restaurant.name %></h5>
            </div>        
          <% end %>
          <% end %>
          </div>
        </div> 
      </div>
  
    </div>
  </div>
</div>