config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do 
      get :feeds
    end

    member do
      get :dashboard
    end
  end
  
  resources :users, only: [:show, :edit, :update]

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants 
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
<<<<<<< HEAD
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
=======
  has_many :favorited_restaurants, thourgh: :favorites, source: :restaurant
>>>>>>> a50d84c42992659eda0c1e93f51e26e328690f76

  def admin?
    self.role == "admin"
  end


end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
 before_action :authenticate_admin

  private
  
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]
  before_action :set_category, only: [:update, :destroy]


  def index
    @categories = Category.all
      if params[:id]
        set_category
      else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end 


  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "Category was successfully updated"
    else
      @category = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "Category was successfully deleted"
    redirect_to admin_categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show 
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  

  def show
    @commented_restaurants = @user.restaurants.uniq
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end


private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>  
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/shared/_restaurant_list.html.erb
    <div class="row">
      <% @restaurants.each do |restaurant| %>
        <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
          <div class="card h-100">
           <!--  <a href="#"><%= image_tag restaurant.image, size:"700x400", class: "img-thumbnail" %></a> -->
           <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded">
            <div class="card-body">
              <h4 class="card-title">
                <a href="#"><%= link_to restaurant.name, restaurant_path(restaurant) %></a>
              </h4>
              <h4 class="card-title">
                <a href="#"><%= restaurant.category.name %></a>
              </h4>
                <p class="card-text"><%= truncate(restaurant.description, length: 80) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <ul class="pagination justify-content-center">
     <%= paginate @restaurants %>
    </ul>
  </div>

  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
    </div>
  </footer>